# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  majorVersion: '1'
  minorVersion: '0'
  patchVersion: '0'

steps:    
- task: CopyFiles@2
  displayName: 'Copy Reports and Folder Structure'
  inputs:
    SourceFolder: $(Build.Repository.LocalPath)
    Contents: |
     **\*
    TargetFolder: '$(build.ArtifactStagingDirectory)/Reports'

- task: DeleteFiles@1
  displayName: 'Removing Project & Build Files'
  inputs:
    SourceFolder: '$(build.ArtifactStagingDirectory)/Reports'
    Contents: |
        **\*.yml
        **\*.sln

- task: DeleteFiles@1
  displayName: 'Removing .git Folder'
  inputs:
    SourceFolder: '$(build.ArtifactStagingDirectory)/Reports/.git'
    Contents: |
        **\*
    RemoveSourceFolder: true

- task: DeleteFiles@1
  displayName: 'Removing .vs Folder'
  inputs:
    SourceFolder: '$(build.ArtifactStagingDirectory)/Reports/.vs'
    Contents: |
        **\*
    RemoveSourceFolder: true

- task: DeleteFiles@1
  displayName: 'Removing Scripts Folder'
  inputs:
    SourceFolder: '$(build.ArtifactStagingDirectory)/Reports/Scripts'
    Contents: |
        **\*
    RemoveSourceFolder: true

- task: ArchiveFiles@2
  displayName: 'Archive Reports Directory'
  inputs:
    rootFolderOrFile: '$(build.ArtifactStagingDirectory)/Reports'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Reports.zip'
    replaceExistingArchive: true

- task: DeleteFiles@1
  displayName: 'Removing Redundent Reports Folder'
  inputs:
    SourceFolder: '$(build.ArtifactStagingDirectory)/Reports'
    Contents: |
        **\*
    RemoveSourceFolder: true

- task: CopyFiles@2
  displayName: 'Copy Scripts'
  inputs:
    SourceFolder: $(Build.Repository.LocalPath)/Scripts
    Contents: |
     *.sql
    TargetFolder: '$(build.ArtifactStagingDirectory)/Scripts'

- task: ArchiveFiles@2
  displayName: 'Archive Scripts'
  inputs:
    rootFolderOrFile: '$(build.ArtifactStagingDirectory)/Scripts'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Scripts.zip'
    replaceExistingArchive: true

- task: DeleteFiles@1
  displayName: 'Removing Redundent Scripts Folder'
  inputs:
    SourceFolder: '$(build.ArtifactStagingDirectory)/Scripts'
    Contents: |
        **\*
    RemoveSourceFolder: true

- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifact'
  inputs:
    targetPath: '$(build.ArtifactStagingDirectory)'
    artifactName: 'Reporting Education Standard $(majorVersion).$(minorVersion).$(patchVersion)'
    artifactType: 'pipeline'
  condition: succeededOrFailed()