# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  majorVersion: '1'
  minorVersion: '0'
  patchVersion: '0'

steps:    
- task: CopyFiles@2
  displayName: 'Copy Reports and Folder Structure'
  inputs:
    SourceFolder: $(Build.Repository.LocalPath)
    Contents: |
     **\*
    TargetFolder: '$(build.ArtifactStagingDirectory)/ReportsDeployment'

- task: DeleteFiles@1
  displayName: 'Removing Project & Build Files'
  inputs:
    SourceFolder: '$(build.ArtifactStagingDirectory)/ReportsDeployment'
    Contents: |
        **\*.yml
        **\*.sln

- task: DeleteFiles@1
  displayName: 'Removing .git Folder'
  inputs:
    SourceFolder: '$(build.ArtifactStagingDirectory)/ReportsDeployment/.git'
    Contents: |
        **\*
    RemoveSourceFolder: true

- task: DeleteFiles@1
  displayName: 'Removing .vs Folder'
  inputs:
    SourceFolder: '$(build.ArtifactStagingDirectory)/ReportsDeployment/.git'
    Contents: |
        **\*
    RemoveSourceFolder: true

- task: ArchiveFiles@2
  displayName: 'Archive Artifact Staging Directory'
  inputs:
    rootFolderOrFile: '$(build.ArtifactStagingDirectory)/ReportsDeployment'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Reports.zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifact'
  inputs:
    targetPath: '$(build.ArtifactStagingDirectory)'
    artifactName: 'Reporting Education Standard $(majorVersion).$(minorVersion).$(patchVersion))'
    artifactType: 'pipeline'
  condition: succeededOrFailed()